<?php
 /**
 * Flickr Feeds
 *
 * @category    Netgo
 * @package     Netgo_Flickrfeeds
 * @author      Afroz Alam <afroz92@gmail.com>
 * @copyright   NetAttingo Technologies (http://www.netattingo.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $userId = Mage::getStoreConfig('flickrfeeds/flickrfeeds/fuserid'); ?>
<?php $limitImg = Mage::getStoreConfig('flickrfeeds/flickrfeeds/limitimg'); ?>
<?php $viewMode = Netgo_Flickrfeeds_Helper_Data::viewmode(); ?>
<?php if($viewMode == 1){ ?>
<script>
	$(document).ready(function(){
		$('#flickrbox').jflickrfeed({
			limit: <?php echo $limitImg; ?>,
			qstrings: {
			id: '<?php echo $userId; ?>'
		},
		cleanDescription: true,
		itemTemplate: '<li>'+
				'<img src="{{image_m}}" alt="{{title}}" />' +
				'<div class="fl-wrap">' +
				'<div class="flickr-title"><span>{{title}}</span>' +
				'</div>' +
				'<a class="more-details" rel="colorbox" href="{{image}}" title="{{description}}">' +
				'more' +
				'</a>' +
				'</div>' +
				 '</li>'
		}, function(data) {
			$('#flickrbox a').colorbox();
		});
	});
</script>
<div id="flickr_container">
	<ul id="flickrbox" class="flickr_thumbs"></ul>
</div>
<?php }else{ ?>
<script>
	$(document).ready(function(){
		$('#flickrbox').jflickrfeed({
			limit: <?php echo $limitImg; ?>,
			qstrings: {
			id: '<?php echo $userId; ?>'
		},
		cleanDescription: true,
		itemTemplate: '<li>'+
				'<img src="{{image_m}}" alt="{{title}}" />' +
				'<div class="fl-wrap">' +
				'<div class="flickr-title"><span>{{title}}</span>' +
				'</div>' +
				'<a class="more-details" rel="colorbox" href="{{image}}" title="{{description}}">' +
				'more' +
				'</a>' +
				'</div>' +
				 '</li>'
		}, function(data) {
			$('#flickrbox a').colorbox();
		});
	});
</script>
<div id="flickr_container_list">
	<ul id="flickrbox" class="flickr_thumbs_list"></ul>
</div>
<?php } ?>
